backend:
  name: github
  repo: Bitraxis/Wera-Creative
  branch: main

media_folder: "/assets/materials/uploads"
public_folder: "/assets/materials/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "/assets/_shop/products"
    create: true
    format: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number", value_type: "float", step: 0.01 }
      - { label: "On Sale", name: "sale", widget: "boolean", default: false }
      - { label: "Sale Price", name: "salePrice", widget: "number", value_type: "float", step: 0.01, required: false }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text", required: false }